#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 3.1.{build}.0
environment:
  gallery_api:
    secure: 9ekJzfsPCDBkyLrfmov83XbbhZ6E2N3z+B/Io8NbDetbHc6hWS19zsDmy7t0Vvxv
install:
    - git clone -q --branch=HashtableCheck https://github.com/SSvilen/DscResource.Tests

    - ps: |
        $moduleName = 'NetworkingDsc'
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -CodeCoverage `
            -CodeCovIo `
            -ExcludeTag @()

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask `
            -Type 'Wiki' `
            -ResourceModuleName $moduleName

        Invoke-AppVeyorDeployTask
